-- OpenFGA-Node-Server: tuple change log.
--
-- Records every write/delete of a tuple in insertion order so the
-- /stores/:storeId/changes endpoint can replay history. Inserts are
-- written transactionally with the underlying tuple mutation by
-- src/storage/tuples.ts so a crash between the two can never leave
-- the changelog out of sync with the tuple state.
--
-- The table lives in the openfga schema for operational simplicity.
-- Like idempotency_keys (see 1777824000000_idempotency-keys.sql), it
-- is NOT part of the OpenFGA-compatible state contract; operators
-- migrating to upstream OpenFGA exclude it from pg_dump:
--
--   pg_dump --schema=openfga \
--           --exclude-table='openfga.idempotency_keys' \
--           --exclude-table='openfga.tuple_change'
--
-- See docs/PRD.md and openfga-bh9 for the full design.

-- The id is a ULID generated by the application so it sorts
-- chronologically (newest = lexically largest). That doubles as a
-- stable cursor for pagination; combining (inserted_at, id) handles
-- the rare case of two changes recorded in the same microsecond.
CREATE TABLE openfga.tuple_change (
  id            text PRIMARY KEY,
  store_id      text NOT NULL REFERENCES openfga.store(id),
  object_type   text NOT NULL,
  object_id     text NOT NULL,
  relation      text NOT NULL,
  user_str      text NOT NULL,
  operation     text NOT NULL CHECK (operation IN ('TUPLE_OPERATION_WRITE', 'TUPLE_OPERATION_DELETE')),
  inserted_at   timestamptz NOT NULL DEFAULT now()
);

-- Newest-first pagination by (inserted_at, id) within a store.
CREATE INDEX idx_tuple_change_store_inserted
  ON openfga.tuple_change (store_id, inserted_at DESC, id DESC);

-- Type-filtered pagination uses object_type as a leading column so
-- the planner can push the predicate before the timestamp scan.
CREATE INDEX idx_tuple_change_store_type_inserted
  ON openfga.tuple_change (store_id, object_type, inserted_at DESC, id DESC);

ALTER TABLE openfga.tuple_change ENABLE ROW LEVEL SECURITY;
