/**
 * OpenFGA-Node-Server: tuple change log.
 *
 * Records every write/delete of a tuple in insertion order so the
 * /stores/:storeId/changes endpoint can replay history. Inserts are
 * written transactionally with the underlying tuple mutation by
 * src/storage/tuples.ts so a crash between the two can never leave
 * the changelog out of sync with the tuple state.
 *
 * Like idempotency_keys, this table is NOT part of the OpenFGA-
 * compatible state contract; operators migrating to upstream OpenFGA
 * exclude it from pg_dump:
 *
 *   pg_dump --schema=<namespace> \
 *           --exclude-table='<namespace>.idempotency_keys' \
 *           --exclude-table='<namespace>.tuple_change'
 *
 * See docs/PRD.md and openfga-bh9 for the full design.
 *
 * Translated from migrations/1777910400000_tuple-changes.sql
 * by openfga-g2j.
 */
import { sql, type Kysely } from 'kysely'
import { getDialect, getNamespace } from '../src/storage/db'
import {
  dialectNow,
  dialectTimestampColumn,
  isPostgres,
} from '../src/storage/dialect'

export async function up(db: Kysely<unknown>): Promise<void> {
  const dialect = getDialect()
  const ns = getNamespace()
  const storeRef = isPostgres(dialect) ? `${ns}.store` : `${ns}_store`

  // The id is a ULID generated by the application so it sorts
  // chronologically (newest = lexically largest). The 1778083200000
  // migration adds a `seq` column for the ORDER-BY tiebreaker on
  // same-millisecond inserts; this initial DDL stops at the
  // newest-first (inserted_at, id) shape openfga-bh9 originally
  // shipped with.
  await db.schema
    .createTable('tuple_change')
    .addColumn('id', 'text', col => col.primaryKey())
    .addColumn('store_id', 'text', col =>
      col.notNull().references(`${storeRef}.id`))
    .addColumn('object_type', 'text', col => col.notNull())
    .addColumn('object_id', 'text', col => col.notNull())
    .addColumn('relation', 'text', col => col.notNull())
    .addColumn('user_str', 'text', col => col.notNull())
    .addColumn('operation', 'text', col =>
      col.notNull().check(sql`operation in ('TUPLE_OPERATION_WRITE', 'TUPLE_OPERATION_DELETE')`))
    .addColumn('inserted_at', dialectTimestampColumn(dialect), col =>
      col.notNull().defaultTo(dialectNow(dialect)))
    .execute()

  // Newest-first pagination by (inserted_at, id) within a store.
  await db.schema
    .createIndex('idx_tuple_change_store_inserted')
    .on('tuple_change')
    .columns(['store_id', 'inserted_at desc', 'id desc'])
    .execute()

  // Type-filtered pagination uses object_type as a leading column so
  // the planner can push the predicate before the timestamp scan.
  await db.schema
    .createIndex('idx_tuple_change_store_type_inserted')
    .on('tuple_change')
    .columns(['store_id', 'object_type', 'inserted_at desc', 'id desc'])
    .execute()

  if (isPostgres(dialect)) {
    await sql`alter table ${sql.id(ns, 'tuple_change')} enable row level security`.execute(db)
  }
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await db.schema.dropTable('tuple_change').execute()
}
