/**
 * OpenFGA-Node-Server: deterministic ordering column on tuple_change.
 *
 * Background: openfga-bh9 created the changelog with `id text` as a
 * ULID generated by src/storage/ids.ts. That implementation uses a
 * random 16-byte suffix on the millisecond timestamp prefix, so two
 * changes recorded in the same millisecond can sort in either order
 * under `ORDER BY id ASC`. Codex's openfga-ra9 review reproduced
 * 8/30 inversions on two same-transaction writes.
 *
 * The OpenFGA ReadChanges contract requires that changes be returned
 * in the exact order they happened. A bigserial sequence column
 * gives Postgres-side monotonic per-insert ordering: each INSERT
 * gets the next sequence value, so ties on `inserted_at` resolve
 * deterministically by insertion order — the order the application
 * iterated the writes/deletes arrays.
 *
 * The id column stays as the primary key (changing the PK would be
 * a much bigger migration); the new seq column is the ORDER-BY key
 * for the changelog and the secondary key in continuation cursors.
 *
 * Postgres path: `seq bigserial NOT NULL UNIQUE` — Postgres handles
 * the auto-assignment.
 *
 * SQLite path: `seq INTEGER NOT NULL UNIQUE` plus a trigger that
 * assigns NEW.rowid to seq AFTER INSERT. SQLite's rowid is
 * monotonically increasing per insert (when the table is
 * non-WITHOUT-ROWID), giving the same insertion-order semantics.
 *
 * Translated from migrations/1778083200000_tuple-change-seq.sql
 * by openfga-g2j.
 */
import { sql, type Kysely } from 'kysely'
import { getDialect, getNamespace } from '../src/storage/db'
import { isPostgres } from '../src/storage/dialect'

export async function up(db: Kysely<unknown>): Promise<void> {
  const dialect = getDialect()
  const ns = getNamespace()
  const physicalTable = isPostgres(dialect) ? `${ns}.tuple_change` : `${ns}_tuple_change`
  const physicalIndex = (name: string) => isPostgres(dialect) ? `${ns}.${name}` : name

  if (isPostgres(dialect)) {
    await sql.raw(`alter table ${physicalTable} add column seq bigserial not null unique`).execute(db)
  }
  else {
    // Two-step on SQLite: add the column with a placeholder default,
    // backfill from rowid for any existing rows, then install a
    // trigger that does the same on every future INSERT.
    await sql.raw(`alter table ${physicalTable} add column seq integer not null default 0`).execute(db)
    await sql.raw(`update ${physicalTable} set seq = rowid`).execute(db)
    await sql.raw(`create unique index idx_${ns}_tuple_change_seq on ${physicalTable} (seq)`).execute(db)
    await sql.raw(
      `create trigger ${ns}_tuple_change_seq_assign
         after insert on ${physicalTable}
         begin
           update ${physicalTable} set seq = NEW.rowid where id = NEW.id;
         end`,
    ).execute(db)
  }

  // Index changes mirror the new ORDER BY clauses in
  // src/storage/tuples.ts. The old (id-tiebroken) indexes are
  // dropped because they no longer match the query plan.
  await sql.raw(`drop index ${physicalIndex('idx_tuple_change_store_inserted')}`).execute(db)
  await sql.raw(`drop index ${physicalIndex('idx_tuple_change_store_type_inserted')}`).execute(db)

  await db.schema
    .createIndex('idx_tuple_change_store_inserted_seq')
    .on('tuple_change')
    .columns(['store_id', 'inserted_at asc', 'seq asc'])
    .execute()

  await db.schema
    .createIndex('idx_tuple_change_store_type_inserted_seq')
    .on('tuple_change')
    .columns(['store_id', 'object_type', 'inserted_at asc', 'seq asc'])
    .execute()
}

export async function down(db: Kysely<unknown>): Promise<void> {
  const dialect = getDialect()
  const ns = getNamespace()
  const physicalTable = isPostgres(dialect) ? `${ns}.tuple_change` : `${ns}_tuple_change`

  await db.schema.dropIndex('idx_tuple_change_store_inserted_seq').execute()
  await db.schema.dropIndex('idx_tuple_change_store_type_inserted_seq').execute()

  if (!isPostgres(dialect)) {
    await sql.raw(`drop trigger ${ns}_tuple_change_seq_assign`).execute(db)
    await sql.raw(`drop index idx_${ns}_tuple_change_seq`).execute(db)
  }

  await sql.raw(`alter table ${physicalTable} drop column seq`).execute(db)

  // Restore the original (id-tiebroken) indexes.
  await db.schema
    .createIndex('idx_tuple_change_store_inserted')
    .on('tuple_change')
    .columns(['store_id', 'inserted_at desc', 'id desc'])
    .execute()

  await db.schema
    .createIndex('idx_tuple_change_store_type_inserted')
    .on('tuple_change')
    .columns(['store_id', 'object_type', 'inserted_at desc', 'id desc'])
    .execute()
}
