-- OpenFGA-Node-Server: deterministic ordering column on tuple_change.
--
-- Background: openfga-bh9 created the changelog with `id text` as a
-- ULID generated by src/storage/ids.ts. That implementation uses a
-- random 16-byte suffix on the millisecond timestamp prefix, so two
-- changes recorded in the same millisecond can sort in either order
-- under `ORDER BY id ASC`. Codex's openfga-ra9 review reproduced
-- 8/30 inversions on two same-transaction writes.
--
-- The OpenFGA ReadChanges contract requires that changes be returned
-- in the exact order they happened. A bigserial sequence column
-- gives Postgres-side monotonic per-insert ordering: each INSERT
-- gets the next sequence value, so ties on `inserted_at` resolve
-- deterministically by insertion order — the order the application
-- iterated the writes/deletes arrays.
--
-- The id column stays as the primary key (changing the PK would be
-- a much bigger migration); the new seq column is the ORDER-BY key
-- for the changelog and the secondary key in continuation cursors.

ALTER TABLE openfga.tuple_change
  ADD COLUMN seq bigserial NOT NULL UNIQUE;

-- Index changes mirror the new ORDER BY clauses in
-- src/storage/tuples.ts. The old (id-tiebroken) indexes are
-- dropped because they no longer match the query plan.
DROP INDEX openfga.idx_tuple_change_store_inserted;
DROP INDEX openfga.idx_tuple_change_store_type_inserted;

CREATE INDEX idx_tuple_change_store_inserted_seq
  ON openfga.tuple_change (store_id, inserted_at ASC, seq ASC);

CREATE INDEX idx_tuple_change_store_type_inserted_seq
  ON openfga.tuple_change (store_id, object_type, inserted_at ASC, seq ASC);
